Fixed an error in wrong definition of tuples in `settings.py`.
